//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializeactionResponse")
inline fun actionResponse(block: ca.berlingoqc.growbe_android_module.proto.ActionResponseKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Message.ActionResponse =
  ca.berlingoqc.growbe_android_module.proto.ActionResponseKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Message.ActionResponse.newBuilder()).apply { block() }._build()
object ActionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Message.ActionResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Message.ActionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Message.ActionResponse = _builder.build()

    /**
     * <code>.ActionCode action = 1;</code>
     */
     var action: ca.berlingoqc.growbe_android_module.proto.Message.ActionCode
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    /**
     * <code>.ActionCode action = 1;</code>
     */
    fun clearAction() {
      _builder.clearAction()
    }

    /**
     * <code>uint32 status = 2;</code>
     */
    var status: kotlin.Int
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <code>uint32 status = 2;</code>
     */
    fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * <code>string msg = 3;</code>
     */
    var msg: kotlin.String
      @JvmName("getMsg")
      get() = _builder.getMsg()
      @JvmName("setMsg")
      set(value) {
        _builder.setMsg(value)
      }
    /**
     * <code>string msg = 3;</code>
     */
    fun clearMsg() {
      _builder.clearMsg()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Message.ActionResponse.copy(block: ca.berlingoqc.growbe_android_module.proto.ActionResponseKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Message.ActionResponse =
  ca.berlingoqc.growbe_android_module.proto.ActionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

