//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializeactorOwnership")
inline fun actorOwnership(block: ca.berlingoqc.growbe_android_module.proto.ActorOwnershipKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership =
  ca.berlingoqc.growbe_android_module.proto.ActorOwnershipKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership.newBuilder()).apply { block() }._build()
object ActorOwnershipKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership = _builder.build()

    /**
     * <code>string moduleId = 1;</code>
     */
    var moduleId: kotlin.String
      @JvmName("getModuleId")
      get() = _builder.getModuleId()
      @JvmName("setModuleId")
      set(value) {
        _builder.setModuleId(value)
      }
    /**
     * <code>string moduleId = 1;</code>
     */
    fun clearModuleId() {
      _builder.clearModuleId()
    }

    /**
     * <code>string property = 2;</code>
     */
    var property: kotlin.String
      @JvmName("getProperty")
      get() = _builder.getProperty()
      @JvmName("setProperty")
      set(value) {
        _builder.setProperty(value)
      }
    /**
     * <code>string property = 2;</code>
     */
    fun clearProperty() {
      _builder.clearProperty()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership.copy(block: ca.berlingoqc.growbe_android_module.proto.ActorOwnershipKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership =
  ca.berlingoqc.growbe_android_module.proto.ActorOwnershipKt.Dsl._create(this.toBuilder()).apply { block() }._build()

