//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializeactorWithOwnership")
inline fun actorWithOwnership(block: ca.berlingoqc.growbe_android_module.proto.ActorWithOwnershipKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.ActorWithOwnership =
  ca.berlingoqc.growbe_android_module.proto.ActorWithOwnershipKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.ActorWithOwnership.newBuilder()).apply { block() }._build()
object ActorWithOwnershipKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.ActorWithOwnership.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.ActorWithOwnership.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.ActorWithOwnership = _builder.build()

    /**
     * <code>.Actor actor = 1;</code>
     */
    var actor: ca.berlingoqc.growbe_android_module.proto.Module.Actor
      @JvmName("getActor")
      get() = _builder.getActor()
      @JvmName("setActor")
      set(value) {
        _builder.setActor(value)
      }
    /**
     * <code>.Actor actor = 1;</code>
     */
    fun clearActor() {
      _builder.clearActor()
    }
    /**
     * <code>.Actor actor = 1;</code>
     * @return Whether the actor field is set.
     */
    fun hasActor(): kotlin.Boolean {
      return _builder.hasActor()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class OwnershipsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .ActorOwnership ownerships = 2;</code>
     */
     val ownerships: com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership, OwnershipsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getOwnershipsList()
      )
    /**
     * <code>repeated .ActorOwnership ownerships = 2;</code>
     * @param value The ownerships to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addOwnerships")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership, OwnershipsProxy>.add(value: ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership) {
      _builder.addOwnerships(value)
    }
    /**
     * <code>repeated .ActorOwnership ownerships = 2;</code>
     * @param value The ownerships to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignOwnerships")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership, OwnershipsProxy>.plusAssign(value: ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership) {
      add(value)
    }
    /**
     * <code>repeated .ActorOwnership ownerships = 2;</code>
     * @param values The ownerships to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllOwnerships")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership, OwnershipsProxy>.addAll(values: kotlin.collections.Iterable<ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership>) {
      _builder.addAllOwnerships(values)
    }
    /**
     * <code>repeated .ActorOwnership ownerships = 2;</code>
     * @param values The ownerships to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllOwnerships")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership, OwnershipsProxy>.plusAssign(values: kotlin.collections.Iterable<ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership>) {
      addAll(values)
    }
    /**
     * <code>repeated .ActorOwnership ownerships = 2;</code>
     * @param index The index to set the value at.
     * @param value The ownerships to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setOwnerships")
    operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership, OwnershipsProxy>.set(index: kotlin.Int, value: ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership) {
      _builder.setOwnerships(index, value)
    }
    /**
     * <code>repeated .ActorOwnership ownerships = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearOwnerships")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.ActorOwnership, OwnershipsProxy>.clear() {
      _builder.clearOwnerships()
    }

  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.ActorWithOwnership.copy(block: ca.berlingoqc.growbe_android_module.proto.ActorWithOwnershipKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.ActorWithOwnership =
  ca.berlingoqc.growbe_android_module.proto.ActorWithOwnershipKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val ca.berlingoqc.growbe_android_module.proto.Module.ActorWithOwnershipOrBuilder.actorOrNull: ca.berlingoqc.growbe_android_module.proto.Module.Actor?
  get() = if (hasActor()) getActor() else null

