//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializeactor")
inline fun actor(block: ca.berlingoqc.growbe_android_module.proto.ActorKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.Actor =
  ca.berlingoqc.growbe_android_module.proto.ActorKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.Actor.newBuilder()).apply { block() }._build()
object ActorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.Actor.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.Actor.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.Actor = _builder.build()

    /**
     * <code>.ActorType type = 1;</code>
     */
     var type: ca.berlingoqc.growbe_android_module.proto.Module.ActorType
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <code>.ActorType type = 1;</code>
     */
    fun clearType() {
      _builder.clearType()
    }

    /**
     * <code>string id = 2;</code>
     */
    var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 2;</code>
     */
    fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string name = 3;</code>
     */
    var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 3;</code>
     */
    fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.Actor.copy(block: ca.berlingoqc.growbe_android_module.proto.ActorKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.Actor =
  ca.berlingoqc.growbe_android_module.proto.ActorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

