//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: alarm.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializealarmZoneValue")
inline fun alarmZoneValue(block: ca.berlingoqc.growbe_android_module.proto.AlarmZoneValueKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue =
  ca.berlingoqc.growbe_android_module.proto.AlarmZoneValueKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue.newBuilder()).apply { block() }._build()
object AlarmZoneValueKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue = _builder.build()

    /**
     * <code>uint32 value = 1;</code>
     */
    var value: kotlin.Int
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * <code>uint32 value = 1;</code>
     */
    fun clearValue() {
      _builder.clearValue()
    }

    /**
     * <code>uint32 offset = 2;</code>
     */
    var offset: kotlin.Int
      @JvmName("getOffset")
      get() = _builder.getOffset()
      @JvmName("setOffset")
      set(value) {
        _builder.setOffset(value)
      }
    /**
     * <code>uint32 offset = 2;</code>
     */
    fun clearOffset() {
      _builder.clearOffset()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue.copy(block: ca.berlingoqc.growbe_android_module.proto.AlarmZoneValueKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue =
  ca.berlingoqc.growbe_android_module.proto.AlarmZoneValueKt.Dsl._create(this.toBuilder()).apply { block() }._build()

