//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializealarmConfig")
inline fun alarmConfig(block: ca.berlingoqc.growbe_android_module.proto.AlarmConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.AlarmConfig =
  ca.berlingoqc.growbe_android_module.proto.AlarmConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.AlarmConfig.newBuilder()).apply { block() }._build()
object AlarmConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.AlarmConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.AlarmConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.AlarmConfig = _builder.build()

    /**
     * <code>.CronItem begining = 1;</code>
     */
    var begining: ca.berlingoqc.growbe_android_module.proto.Module.CronItem
      @JvmName("getBegining")
      get() = _builder.getBegining()
      @JvmName("setBegining")
      set(value) {
        _builder.setBegining(value)
      }
    /**
     * <code>.CronItem begining = 1;</code>
     */
    fun clearBegining() {
      _builder.clearBegining()
    }
    /**
     * <code>.CronItem begining = 1;</code>
     * @return Whether the begining field is set.
     */
    fun hasBegining(): kotlin.Boolean {
      return _builder.hasBegining()
    }

    /**
     * <code>.CronItem end = 2;</code>
     */
    var end: ca.berlingoqc.growbe_android_module.proto.Module.CronItem
      @JvmName("getEnd")
      get() = _builder.getEnd()
      @JvmName("setEnd")
      set(value) {
        _builder.setEnd(value)
      }
    /**
     * <code>.CronItem end = 2;</code>
     */
    fun clearEnd() {
      _builder.clearEnd()
    }
    /**
     * <code>.CronItem end = 2;</code>
     * @return Whether the end field is set.
     */
    fun hasEnd(): kotlin.Boolean {
      return _builder.hasEnd()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.AlarmConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.AlarmConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.AlarmConfig =
  ca.berlingoqc.growbe_android_module.proto.AlarmConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val ca.berlingoqc.growbe_android_module.proto.Module.AlarmConfigOrBuilder.beginingOrNull: ca.berlingoqc.growbe_android_module.proto.Module.CronItem?
  get() = if (hasBegining()) getBegining() else null

val ca.berlingoqc.growbe_android_module.proto.Module.AlarmConfigOrBuilder.endOrNull: ca.berlingoqc.growbe_android_module.proto.Module.CronItem?
  get() = if (hasEnd()) getEnd() else null

