//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: board.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializecomboardConfig")
inline fun comboardConfig(block: ca.berlingoqc.growbe_android_module.proto.ComboardConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.ComboardConfig =
  ca.berlingoqc.growbe_android_module.proto.ComboardConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Board.ComboardConfig.newBuilder()).apply { block() }._build()
object ComboardConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Board.ComboardConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Board.ComboardConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Board.ComboardConfig = _builder.build()

    /**
     * <code>string config = 1;</code>
     */
    var config: kotlin.String
      @JvmName("getConfig")
      get() = _builder.getConfig()
      @JvmName("setConfig")
      set(value) {
        _builder.setConfig(value)
      }
    /**
     * <code>string config = 1;</code>
     */
    fun clearConfig() {
      _builder.clearConfig()
    }

    /**
     * <code>string imple = 2;</code>
     */
    var imple: kotlin.String
      @JvmName("getImple")
      get() = _builder.getImple()
      @JvmName("setImple")
      set(value) {
        _builder.setImple(value)
      }
    /**
     * <code>string imple = 2;</code>
     */
    fun clearImple() {
      _builder.clearImple()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Board.ComboardConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.ComboardConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.ComboardConfig =
  ca.berlingoqc.growbe_android_module.proto.ComboardConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

