//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializecronItem")
inline fun cronItem(block: ca.berlingoqc.growbe_android_module.proto.CronItemKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.CronItem =
  ca.berlingoqc.growbe_android_module.proto.CronItemKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.CronItem.newBuilder()).apply { block() }._build()
object CronItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.CronItem.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.CronItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.CronItem = _builder.build()

    /**
     * <code>int32 minute = 1;</code>
     */
    var minute: kotlin.Int
      @JvmName("getMinute")
      get() = _builder.getMinute()
      @JvmName("setMinute")
      set(value) {
        _builder.setMinute(value)
      }
    /**
     * <code>int32 minute = 1;</code>
     */
    fun clearMinute() {
      _builder.clearMinute()
    }

    /**
     * <code>int32 hour = 2;</code>
     */
    var hour: kotlin.Int
      @JvmName("getHour")
      get() = _builder.getHour()
      @JvmName("setHour")
      set(value) {
        _builder.setHour(value)
      }
    /**
     * <code>int32 hour = 2;</code>
     */
    fun clearHour() {
      _builder.clearHour()
    }

    /**
     * <code>int32 dayMonth = 3;</code>
     */
    var dayMonth: kotlin.Int
      @JvmName("getDayMonth")
      get() = _builder.getDayMonth()
      @JvmName("setDayMonth")
      set(value) {
        _builder.setDayMonth(value)
      }
    /**
     * <code>int32 dayMonth = 3;</code>
     */
    fun clearDayMonth() {
      _builder.clearDayMonth()
    }

    /**
     * <code>int32 month = 4;</code>
     */
    var month: kotlin.Int
      @JvmName("getMonth")
      get() = _builder.getMonth()
      @JvmName("setMonth")
      set(value) {
        _builder.setMonth(value)
      }
    /**
     * <code>int32 month = 4;</code>
     */
    fun clearMonth() {
      _builder.clearMonth()
    }

    /**
     * <code>int32 dayWeek = 5;</code>
     */
    var dayWeek: kotlin.Int
      @JvmName("getDayWeek")
      get() = _builder.getDayWeek()
      @JvmName("setDayWeek")
      set(value) {
        _builder.setDayWeek(value)
      }
    /**
     * <code>int32 dayWeek = 5;</code>
     */
    fun clearDayWeek() {
      _builder.clearDayWeek()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.CronItem.copy(block: ca.berlingoqc.growbe_android_module.proto.CronItemKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.CronItem =
  ca.berlingoqc.growbe_android_module.proto.CronItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

