//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializecycleConfig")
inline fun cycleConfig(block: ca.berlingoqc.growbe_android_module.proto.CycleConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.CycleConfig =
  ca.berlingoqc.growbe_android_module.proto.CycleConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.CycleConfig.newBuilder()).apply { block() }._build()
object CycleConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.CycleConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.CycleConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.CycleConfig = _builder.build()

    /**
     * <code>int32 waitingTime = 1;</code>
     */
    var waitingTime: kotlin.Int
      @JvmName("getWaitingTime")
      get() = _builder.getWaitingTime()
      @JvmName("setWaitingTime")
      set(value) {
        _builder.setWaitingTime(value)
      }
    /**
     * <code>int32 waitingTime = 1;</code>
     */
    fun clearWaitingTime() {
      _builder.clearWaitingTime()
    }

    /**
     * <code>int32 runningTime = 2;</code>
     */
    var runningTime: kotlin.Int
      @JvmName("getRunningTime")
      get() = _builder.getRunningTime()
      @JvmName("setRunningTime")
      set(value) {
        _builder.setRunningTime(value)
      }
    /**
     * <code>int32 runningTime = 2;</code>
     */
    fun clearRunningTime() {
      _builder.clearRunningTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.CycleConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.CycleConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.CycleConfig =
  ca.berlingoqc.growbe_android_module.proto.CycleConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

