//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: alarm.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializefieldAlarm")
inline fun fieldAlarm(block: ca.berlingoqc.growbe_android_module.proto.FieldAlarmKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Alarm.FieldAlarm =
  ca.berlingoqc.growbe_android_module.proto.FieldAlarmKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Alarm.FieldAlarm.newBuilder()).apply { block() }._build()
object FieldAlarmKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Alarm.FieldAlarm.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Alarm.FieldAlarm.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Alarm.FieldAlarm = _builder.build()

    /**
     * <code>string moduleId = 1;</code>
     */
    var moduleId: kotlin.String
      @JvmName("getModuleId")
      get() = _builder.getModuleId()
      @JvmName("setModuleId")
      set(value) {
        _builder.setModuleId(value)
      }
    /**
     * <code>string moduleId = 1;</code>
     */
    fun clearModuleId() {
      _builder.clearModuleId()
    }

    /**
     * <code>string property = 2;</code>
     */
    var property: kotlin.String
      @JvmName("getProperty")
      get() = _builder.getProperty()
      @JvmName("setProperty")
      set(value) {
        _builder.setProperty(value)
      }
    /**
     * <code>string property = 2;</code>
     */
    fun clearProperty() {
      _builder.clearProperty()
    }

    /**
     * <code>.AlarmZoneValue veryLow = 3;</code>
     */
    var veryLow: ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue
      @JvmName("getVeryLow")
      get() = _builder.getVeryLow()
      @JvmName("setVeryLow")
      set(value) {
        _builder.setVeryLow(value)
      }
    /**
     * <code>.AlarmZoneValue veryLow = 3;</code>
     */
    fun clearVeryLow() {
      _builder.clearVeryLow()
    }
    /**
     * <code>.AlarmZoneValue veryLow = 3;</code>
     * @return Whether the veryLow field is set.
     */
    fun hasVeryLow(): kotlin.Boolean {
      return _builder.hasVeryLow()
    }

    /**
     * <code>.AlarmZoneValue low = 4;</code>
     */
    var low: ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue
      @JvmName("getLow")
      get() = _builder.getLow()
      @JvmName("setLow")
      set(value) {
        _builder.setLow(value)
      }
    /**
     * <code>.AlarmZoneValue low = 4;</code>
     */
    fun clearLow() {
      _builder.clearLow()
    }
    /**
     * <code>.AlarmZoneValue low = 4;</code>
     * @return Whether the low field is set.
     */
    fun hasLow(): kotlin.Boolean {
      return _builder.hasLow()
    }

    /**
     * <code>.AlarmZoneValue high = 5;</code>
     */
    var high: ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue
      @JvmName("getHigh")
      get() = _builder.getHigh()
      @JvmName("setHigh")
      set(value) {
        _builder.setHigh(value)
      }
    /**
     * <code>.AlarmZoneValue high = 5;</code>
     */
    fun clearHigh() {
      _builder.clearHigh()
    }
    /**
     * <code>.AlarmZoneValue high = 5;</code>
     * @return Whether the high field is set.
     */
    fun hasHigh(): kotlin.Boolean {
      return _builder.hasHigh()
    }

    /**
     * <code>.AlarmZoneValue veryHigh = 6;</code>
     */
    var veryHigh: ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue
      @JvmName("getVeryHigh")
      get() = _builder.getVeryHigh()
      @JvmName("setVeryHigh")
      set(value) {
        _builder.setVeryHigh(value)
      }
    /**
     * <code>.AlarmZoneValue veryHigh = 6;</code>
     */
    fun clearVeryHigh() {
      _builder.clearVeryHigh()
    }
    /**
     * <code>.AlarmZoneValue veryHigh = 6;</code>
     * @return Whether the veryHigh field is set.
     */
    fun hasVeryHigh(): kotlin.Boolean {
      return _builder.hasVeryHigh()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Alarm.FieldAlarm.copy(block: ca.berlingoqc.growbe_android_module.proto.FieldAlarmKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Alarm.FieldAlarm =
  ca.berlingoqc.growbe_android_module.proto.FieldAlarmKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val ca.berlingoqc.growbe_android_module.proto.Alarm.FieldAlarmOrBuilder.veryLowOrNull: ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue?
  get() = if (hasVeryLow()) getVeryLow() else null

val ca.berlingoqc.growbe_android_module.proto.Alarm.FieldAlarmOrBuilder.lowOrNull: ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue?
  get() = if (hasLow()) getLow() else null

val ca.berlingoqc.growbe_android_module.proto.Alarm.FieldAlarmOrBuilder.highOrNull: ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue?
  get() = if (hasHigh()) getHigh() else null

val ca.berlingoqc.growbe_android_module.proto.Alarm.FieldAlarmOrBuilder.veryHighOrNull: ca.berlingoqc.growbe_android_module.proto.Alarm.AlarmZoneValue?
  get() = if (hasVeryHigh()) getVeryHigh() else null

