//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializegrowbeMessage")
inline fun growbeMessage(block: ca.berlingoqc.growbe_android_module.proto.GrowbeMessageKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Message.GrowbeMessage =
  ca.berlingoqc.growbe_android_module.proto.GrowbeMessageKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Message.GrowbeMessage.newBuilder()).apply { block() }._build()
object GrowbeMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Message.GrowbeMessage.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Message.GrowbeMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Message.GrowbeMessage = _builder.build()

    /**
     * <code>string topic = 1;</code>
     */
    var topic: kotlin.String
      @JvmName("getTopic")
      get() = _builder.getTopic()
      @JvmName("setTopic")
      set(value) {
        _builder.setTopic(value)
      }
    /**
     * <code>string topic = 1;</code>
     */
    fun clearTopic() {
      _builder.clearTopic()
    }

    /**
     * <code>int32 messageType = 2;</code>
     */
    var messageType: kotlin.Int
      @JvmName("getMessageType")
      get() = _builder.getMessageType()
      @JvmName("setMessageType")
      set(value) {
        _builder.setMessageType(value)
      }
    /**
     * <code>int32 messageType = 2;</code>
     */
    fun clearMessageType() {
      _builder.clearMessageType()
    }

    /**
     * <code>bytes body = 3;</code>
     */
    var body: com.google.protobuf.ByteString
      @JvmName("getBody")
      get() = _builder.getBody()
      @JvmName("setBody")
      set(value) {
        _builder.setBody(value)
      }
    /**
     * <code>bytes body = 3;</code>
     */
    fun clearBody() {
      _builder.clearBody()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Message.GrowbeMessage.copy(block: ca.berlingoqc.growbe_android_module.proto.GrowbeMessageKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Message.GrowbeMessage =
  ca.berlingoqc.growbe_android_module.proto.GrowbeMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

