//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializehearthBeath")
inline fun hearthBeath(block: ca.berlingoqc.growbe_android_module.proto.HearthBeathKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Message.HearthBeath =
  ca.berlingoqc.growbe_android_module.proto.HearthBeathKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Message.HearthBeath.newBuilder()).apply { block() }._build()
object HearthBeathKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Message.HearthBeath.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Message.HearthBeath.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Message.HearthBeath = _builder.build()

    /**
     * <code>string rtc = 2;</code>
     */
    var rtc: kotlin.String
      @JvmName("getRtc")
      get() = _builder.getRtc()
      @JvmName("setRtc")
      set(value) {
        _builder.setRtc(value)
      }
    /**
     * <code>string rtc = 2;</code>
     */
    fun clearRtc() {
      _builder.clearRtc()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Message.HearthBeath.copy(block: ca.berlingoqc.growbe_android_module.proto.HearthBeathKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Message.HearthBeath =
  ca.berlingoqc.growbe_android_module.proto.HearthBeathKt.Dsl._create(this.toBuilder()).apply { block() }._build()

