//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: board.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializehttpServerConfig")
inline fun httpServerConfig(block: ca.berlingoqc.growbe_android_module.proto.HttpServerConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.HttpServerConfig =
  ca.berlingoqc.growbe_android_module.proto.HttpServerConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Board.HttpServerConfig.newBuilder()).apply { block() }._build()
object HttpServerConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Board.HttpServerConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Board.HttpServerConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Board.HttpServerConfig = _builder.build()

    /**
     * <code>string addr = 1;</code>
     */
    var addr: kotlin.String
      @JvmName("getAddr")
      get() = _builder.getAddr()
      @JvmName("setAddr")
      set(value) {
        _builder.setAddr(value)
      }
    /**
     * <code>string addr = 1;</code>
     */
    fun clearAddr() {
      _builder.clearAddr()
    }

    /**
     * <code>int32 port = 2;</code>
     */
    var port: kotlin.Int
      @JvmName("getPort")
      get() = _builder.getPort()
      @JvmName("setPort")
      set(value) {
        _builder.setPort(value)
      }
    /**
     * <code>int32 port = 2;</code>
     */
    fun clearPort() {
      _builder.clearPort()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Board.HttpServerConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.HttpServerConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.HttpServerConfig =
  ca.berlingoqc.growbe_android_module.proto.HttpServerConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

