//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: board.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializeloggerConfig")
inline fun loggerConfig(block: ca.berlingoqc.growbe_android_module.proto.LoggerConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.LoggerConfig =
  ca.berlingoqc.growbe_android_module.proto.LoggerConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Board.LoggerConfig.newBuilder()).apply { block() }._build()
object LoggerConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Board.LoggerConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Board.LoggerConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Board.LoggerConfig = _builder.build()

    /**
     * <code>string target = 1;</code>
     */
    var target: kotlin.String
      @JvmName("getTarget")
      get() = _builder.getTarget()
      @JvmName("setTarget")
      set(value) {
        _builder.setTarget(value)
      }
    /**
     * <code>string target = 1;</code>
     */
    fun clearTarget() {
      _builder.clearTarget()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Board.LoggerConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.LoggerConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.LoggerConfig =
  ca.berlingoqc.growbe_android_module.proto.LoggerConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

