//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializemanualConfig")
inline fun manualConfig(block: ca.berlingoqc.growbe_android_module.proto.ManualConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.ManualConfig =
  ca.berlingoqc.growbe_android_module.proto.ManualConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.ManualConfig.newBuilder()).apply { block() }._build()
object ManualConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.ManualConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.ManualConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.ManualConfig = _builder.build()

    /**
     * <code>bool state = 1;</code>
     */
    var state: kotlin.Boolean
      @JvmName("getState")
      get() = _builder.getState()
      @JvmName("setState")
      set(value) {
        _builder.setState(value)
      }
    /**
     * <code>bool state = 1;</code>
     */
    fun clearState() {
      _builder.clearState()
    }

    /**
     * <code>int32 duration = 2;</code>
     */
    var duration: kotlin.Int
      @JvmName("getDuration")
      get() = _builder.getDuration()
      @JvmName("setDuration")
      set(value) {
        _builder.setDuration(value)
      }
    /**
     * <code>int32 duration = 2;</code>
     */
    fun clearDuration() {
      _builder.clearDuration()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.ManualConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.ManualConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.ManualConfig =
  ca.berlingoqc.growbe_android_module.proto.ManualConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

