//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializemoduleData")
inline fun moduleData(block: ca.berlingoqc.growbe_android_module.proto.ModuleDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.ModuleData =
  ca.berlingoqc.growbe_android_module.proto.ModuleDataKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.ModuleData.newBuilder()).apply { block() }._build()
object ModuleDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.ModuleData.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.ModuleData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.ModuleData = _builder.build()

    /**
     * <code>string id = 1;</code>
     */
    var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 1;</code>
     */
    fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string name = 2;</code>
     */
    var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 2;</code>
     */
    fun clearName() {
      _builder.clearName()
    }

    /**
     * <code>int32 readCount = 4;</code>
     */
    var readCount: kotlin.Int
      @JvmName("getReadCount")
      get() = _builder.getReadCount()
      @JvmName("setReadCount")
      set(value) {
        _builder.setReadCount(value)
      }
    /**
     * <code>int32 readCount = 4;</code>
     */
    fun clearReadCount() {
      _builder.clearReadCount()
    }

    /**
     * <code>string boardVersion = 5;</code>
     */
    var boardVersion: kotlin.String
      @JvmName("getBoardVersion")
      get() = _builder.getBoardVersion()
      @JvmName("setBoardVersion")
      set(value) {
        _builder.setBoardVersion(value)
      }
    /**
     * <code>string boardVersion = 5;</code>
     */
    fun clearBoardVersion() {
      _builder.clearBoardVersion()
    }

    /**
     * <code>bool plug = 6;</code>
     */
    var plug: kotlin.Boolean
      @JvmName("getPlug")
      get() = _builder.getPlug()
      @JvmName("setPlug")
      set(value) {
        _builder.setPlug(value)
      }
    /**
     * <code>bool plug = 6;</code>
     */
    fun clearPlug() {
      _builder.clearPlug()
    }

    /**
     * <code>int32 atIndex = 7;</code>
     */
    var atIndex: kotlin.Int
      @JvmName("getAtIndex")
      get() = _builder.getAtIndex()
      @JvmName("setAtIndex")
      set(value) {
        _builder.setAtIndex(value)
      }
    /**
     * <code>int32 atIndex = 7;</code>
     */
    fun clearAtIndex() {
      _builder.clearAtIndex()
    }

    /**
     * <code>string board = 8;</code>
     */
    var board: kotlin.String
      @JvmName("getBoard")
      get() = _builder.getBoard()
      @JvmName("setBoard")
      set(value) {
        _builder.setBoard(value)
      }
    /**
     * <code>string board = 8;</code>
     */
    fun clearBoard() {
      _builder.clearBoard()
    }

    /**
     * <code>string boardAddr = 9;</code>
     */
    var boardAddr: kotlin.String
      @JvmName("getBoardAddr")
      get() = _builder.getBoardAddr()
      @JvmName("setBoardAddr")
      set(value) {
        _builder.setBoardAddr(value)
      }
    /**
     * <code>string boardAddr = 9;</code>
     */
    fun clearBoardAddr() {
      _builder.clearBoardAddr()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.ModuleData.copy(block: ca.berlingoqc.growbe_android_module.proto.ModuleDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.ModuleData =
  ca.berlingoqc.growbe_android_module.proto.ModuleDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

