//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: board.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializemQTTConfig")
inline fun mQTTConfig(block: ca.berlingoqc.growbe_android_module.proto.MQTTConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.MQTTConfig =
  ca.berlingoqc.growbe_android_module.proto.MQTTConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Board.MQTTConfig.newBuilder()).apply { block() }._build()
object MQTTConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Board.MQTTConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Board.MQTTConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Board.MQTTConfig = _builder.build()

    /**
     * <code>string url = 1;</code>
     */
    var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.getUrl()
      @JvmName("setUrl")
      set(value) {
        _builder.setUrl(value)
      }
    /**
     * <code>string url = 1;</code>
     */
    fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * <code>int32 port = 2;</code>
     */
    var port: kotlin.Int
      @JvmName("getPort")
      get() = _builder.getPort()
      @JvmName("setPort")
      set(value) {
        _builder.setPort(value)
      }
    /**
     * <code>int32 port = 2;</code>
     */
    fun clearPort() {
      _builder.clearPort()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Board.MQTTConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.MQTTConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.MQTTConfig =
  ca.berlingoqc.growbe_android_module.proto.MQTTConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

