//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializephonePressureData")
inline fun phonePressureData(block: ca.berlingoqc.growbe_android_module.proto.PhonePressureDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureData =
  ca.berlingoqc.growbe_android_module.proto.PhonePressureDataKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureData.newBuilder()).apply { block() }._build()
object PhonePressureDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureData.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureData = _builder.build()

    /**
     * <code>float hpa = 1;</code>
     */
    var hpa: kotlin.Float
      @JvmName("getHpa")
      get() = _builder.getHpa()
      @JvmName("setHpa")
      set(value) {
        _builder.setHpa(value)
      }
    /**
     * <code>float hpa = 1;</code>
     */
    fun clearHpa() {
      _builder.clearHpa()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureData.copy(block: ca.berlingoqc.growbe_android_module.proto.PhonePressureDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureData =
  ca.berlingoqc.growbe_android_module.proto.PhonePressureDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

