//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializephoneAmbientLightConfig")
inline fun phoneAmbientLightConfig(block: ca.berlingoqc.growbe_android_module.proto.PhoneAmbientLightConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhoneAmbientLightConfig =
  ca.berlingoqc.growbe_android_module.proto.PhoneAmbientLightConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.PhoneAmbientLightConfig.newBuilder()).apply { block() }._build()
object PhoneAmbientLightConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.PhoneAmbientLightConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.PhoneAmbientLightConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.PhoneAmbientLightConfig = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.PhoneAmbientLightConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.PhoneAmbientLightConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhoneAmbientLightConfig =
  ca.berlingoqc.growbe_android_module.proto.PhoneAmbientLightConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

