//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializephoneModuleData")
inline fun phoneModuleData(block: ca.berlingoqc.growbe_android_module.proto.PhoneModuleDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleData =
  ca.berlingoqc.growbe_android_module.proto.PhoneModuleDataKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleData.newBuilder()).apply { block() }._build()
object PhoneModuleDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleData.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleData = _builder.build()

    /**
     * <code>.PhonePosition position = 1;</code>
     */
    var position: ca.berlingoqc.growbe_android_module.proto.Module.PhonePosition
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * <code>.PhonePosition position = 1;</code>
     */
    fun clearPosition() {
      _builder.clearPosition()
    }
    /**
     * <code>.PhonePosition position = 1;</code>
     * @return Whether the position field is set.
     */
    fun hasPosition(): kotlin.Boolean {
      return _builder.hasPosition()
    }

    /**
     * <code>.PhoneAcceleration acceleration = 2;</code>
     */
    var acceleration: ca.berlingoqc.growbe_android_module.proto.Module.PhoneAcceleration
      @JvmName("getAcceleration")
      get() = _builder.getAcceleration()
      @JvmName("setAcceleration")
      set(value) {
        _builder.setAcceleration(value)
      }
    /**
     * <code>.PhoneAcceleration acceleration = 2;</code>
     */
    fun clearAcceleration() {
      _builder.clearAcceleration()
    }
    /**
     * <code>.PhoneAcceleration acceleration = 2;</code>
     * @return Whether the acceleration field is set.
     */
    fun hasAcceleration(): kotlin.Boolean {
      return _builder.hasAcceleration()
    }

    /**
     * <code>.PhoneAmbientLight light = 3;</code>
     */
    var light: ca.berlingoqc.growbe_android_module.proto.Module.PhoneAmbientLight
      @JvmName("getLight")
      get() = _builder.getLight()
      @JvmName("setLight")
      set(value) {
        _builder.setLight(value)
      }
    /**
     * <code>.PhoneAmbientLight light = 3;</code>
     */
    fun clearLight() {
      _builder.clearLight()
    }
    /**
     * <code>.PhoneAmbientLight light = 3;</code>
     * @return Whether the light field is set.
     */
    fun hasLight(): kotlin.Boolean {
      return _builder.hasLight()
    }

    /**
     * <code>.PhonePressure pressure = 5;</code>
     */
    var pressure: ca.berlingoqc.growbe_android_module.proto.Module.PhonePressure
      @JvmName("getPressure")
      get() = _builder.getPressure()
      @JvmName("setPressure")
      set(value) {
        _builder.setPressure(value)
      }
    /**
     * <code>.PhonePressure pressure = 5;</code>
     */
    fun clearPressure() {
      _builder.clearPressure()
    }
    /**
     * <code>.PhonePressure pressure = 5;</code>
     * @return Whether the pressure field is set.
     */
    fun hasPressure(): kotlin.Boolean {
      return _builder.hasPressure()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleData.copy(block: ca.berlingoqc.growbe_android_module.proto.PhoneModuleDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleData =
  ca.berlingoqc.growbe_android_module.proto.PhoneModuleDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleDataOrBuilder.positionOrNull: ca.berlingoqc.growbe_android_module.proto.Module.PhonePosition?
  get() = if (hasPosition()) getPosition() else null

val ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleDataOrBuilder.accelerationOrNull: ca.berlingoqc.growbe_android_module.proto.Module.PhoneAcceleration?
  get() = if (hasAcceleration()) getAcceleration() else null

val ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleDataOrBuilder.lightOrNull: ca.berlingoqc.growbe_android_module.proto.Module.PhoneAmbientLight?
  get() = if (hasLight()) getLight() else null

val ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleDataOrBuilder.pressureOrNull: ca.berlingoqc.growbe_android_module.proto.Module.PhonePressure?
  get() = if (hasPressure()) getPressure() else null

