//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializephonePositionConfig")
inline fun phonePositionConfig(block: ca.berlingoqc.growbe_android_module.proto.PhonePositionConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionConfig =
  ca.berlingoqc.growbe_android_module.proto.PhonePositionConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionConfig.newBuilder()).apply { block() }._build()
object PhonePositionConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionConfig = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.PhonePositionConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionConfig =
  ca.berlingoqc.growbe_android_module.proto.PhonePositionConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

