//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializephonePositionData")
inline fun phonePositionData(block: ca.berlingoqc.growbe_android_module.proto.PhonePositionDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionData =
  ca.berlingoqc.growbe_android_module.proto.PhonePositionDataKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionData.newBuilder()).apply { block() }._build()
object PhonePositionDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionData.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionData = _builder.build()

    /**
     * <code>float lat = 1;</code>
     */
    var lat: kotlin.Float
      @JvmName("getLat")
      get() = _builder.getLat()
      @JvmName("setLat")
      set(value) {
        _builder.setLat(value)
      }
    /**
     * <code>float lat = 1;</code>
     */
    fun clearLat() {
      _builder.clearLat()
    }

    /**
     * <code>float log = 2;</code>
     */
    var log: kotlin.Float
      @JvmName("getLog")
      get() = _builder.getLog()
      @JvmName("setLog")
      set(value) {
        _builder.setLog(value)
      }
    /**
     * <code>float log = 2;</code>
     */
    fun clearLog() {
      _builder.clearLog()
    }

    /**
     * <code>float accuracy = 3;</code>
     */
    var accuracy: kotlin.Float
      @JvmName("getAccuracy")
      get() = _builder.getAccuracy()
      @JvmName("setAccuracy")
      set(value) {
        _builder.setAccuracy(value)
      }
    /**
     * <code>float accuracy = 3;</code>
     */
    fun clearAccuracy() {
      _builder.clearAccuracy()
    }

    /**
     * <code>double altitude = 4;</code>
     */
    var altitude: kotlin.Double
      @JvmName("getAltitude")
      get() = _builder.getAltitude()
      @JvmName("setAltitude")
      set(value) {
        _builder.setAltitude(value)
      }
    /**
     * <code>double altitude = 4;</code>
     */
    fun clearAltitude() {
      _builder.clearAltitude()
    }

    /**
     * <code>float bearing = 5;</code>
     */
    var bearing: kotlin.Float
      @JvmName("getBearing")
      get() = _builder.getBearing()
      @JvmName("setBearing")
      set(value) {
        _builder.setBearing(value)
      }
    /**
     * <code>float bearing = 5;</code>
     */
    fun clearBearing() {
      _builder.clearBearing()
    }

    /**
     * <code>float speed = 7;</code>
     */
    var speed: kotlin.Float
      @JvmName("getSpeed")
      get() = _builder.getSpeed()
      @JvmName("setSpeed")
      set(value) {
        _builder.setSpeed(value)
      }
    /**
     * <code>float speed = 7;</code>
     */
    fun clearSpeed() {
      _builder.clearSpeed()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionData.copy(block: ca.berlingoqc.growbe_android_module.proto.PhonePositionDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhonePositionData =
  ca.berlingoqc.growbe_android_module.proto.PhonePositionDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

