//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializephoneStreamingData")
inline fun phoneStreamingData(block: ca.berlingoqc.growbe_android_module.proto.PhoneStreamingDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingData =
  ca.berlingoqc.growbe_android_module.proto.PhoneStreamingDataKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingData.newBuilder()).apply { block() }._build()
object PhoneStreamingDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingData.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingData = _builder.build()

    /**
     * <code>string status = 1;</code>
     */
    var status: kotlin.String
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <code>string status = 1;</code>
     */
    fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * <code>float fps = 2;</code>
     */
    var fps: kotlin.Float
      @JvmName("getFps")
      get() = _builder.getFps()
      @JvmName("setFps")
      set(value) {
        _builder.setFps(value)
      }
    /**
     * <code>float fps = 2;</code>
     */
    fun clearFps() {
      _builder.clearFps()
    }

    /**
     * <code>float bitrate = 3;</code>
     */
    var bitrate: kotlin.Float
      @JvmName("getBitrate")
      get() = _builder.getBitrate()
      @JvmName("setBitrate")
      set(value) {
        _builder.setBitrate(value)
      }
    /**
     * <code>float bitrate = 3;</code>
     */
    fun clearBitrate() {
      _builder.clearBitrate()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingData.copy(block: ca.berlingoqc.growbe_android_module.proto.PhoneStreamingDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingData =
  ca.berlingoqc.growbe_android_module.proto.PhoneStreamingDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

