//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializephoneAcceleration")
inline fun phoneAcceleration(block: ca.berlingoqc.growbe_android_module.proto.PhoneAccelerationKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhoneAcceleration =
  ca.berlingoqc.growbe_android_module.proto.PhoneAccelerationKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.PhoneAcceleration.newBuilder()).apply { block() }._build()
object PhoneAccelerationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.PhoneAcceleration.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.PhoneAcceleration.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.PhoneAcceleration = _builder.build()

    /**
     * <code>float gx = 1;</code>
     */
    var gx: kotlin.Float
      @JvmName("getGx")
      get() = _builder.getGx()
      @JvmName("setGx")
      set(value) {
        _builder.setGx(value)
      }
    /**
     * <code>float gx = 1;</code>
     */
    fun clearGx() {
      _builder.clearGx()
    }

    /**
     * <code>float gy = 2;</code>
     */
    var gy: kotlin.Float
      @JvmName("getGy")
      get() = _builder.getGy()
      @JvmName("setGy")
      set(value) {
        _builder.setGy(value)
      }
    /**
     * <code>float gy = 2;</code>
     */
    fun clearGy() {
      _builder.clearGy()
    }

    /**
     * <code>float gz = 3;</code>
     */
    var gz: kotlin.Float
      @JvmName("getGz")
      get() = _builder.getGz()
      @JvmName("setGz")
      set(value) {
        _builder.setGz(value)
      }
    /**
     * <code>float gz = 3;</code>
     */
    fun clearGz() {
      _builder.clearGz()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.PhoneAcceleration.copy(block: ca.berlingoqc.growbe_android_module.proto.PhoneAccelerationKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhoneAcceleration =
  ca.berlingoqc.growbe_android_module.proto.PhoneAccelerationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

