//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializephoneModuleConfig")
inline fun phoneModuleConfig(block: ca.berlingoqc.growbe_android_module.proto.PhoneModuleConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleConfig =
  ca.berlingoqc.growbe_android_module.proto.PhoneModuleConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleConfig.newBuilder()).apply { block() }._build()
object PhoneModuleConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleConfig = _builder.build()

    /**
     * <code>bool sensor_position = 1;</code>
     */
    var sensorPosition: kotlin.Boolean
      @JvmName("getSensorPosition")
      get() = _builder.getSensorPosition()
      @JvmName("setSensorPosition")
      set(value) {
        _builder.setSensorPosition(value)
      }
    /**
     * <code>bool sensor_position = 1;</code>
     */
    fun clearSensorPosition() {
      _builder.clearSensorPosition()
    }

    /**
     * <code>bool sensor_accel = 2;</code>
     */
    var sensorAccel: kotlin.Boolean
      @JvmName("getSensorAccel")
      get() = _builder.getSensorAccel()
      @JvmName("setSensorAccel")
      set(value) {
        _builder.setSensorAccel(value)
      }
    /**
     * <code>bool sensor_accel = 2;</code>
     */
    fun clearSensorAccel() {
      _builder.clearSensorAccel()
    }

    /**
     * <code>bool sensor_light = 3;</code>
     */
    var sensorLight: kotlin.Boolean
      @JvmName("getSensorLight")
      get() = _builder.getSensorLight()
      @JvmName("setSensorLight")
      set(value) {
        _builder.setSensorLight(value)
      }
    /**
     * <code>bool sensor_light = 3;</code>
     */
    fun clearSensorLight() {
      _builder.clearSensorLight()
    }

    /**
     * <code>bool sensor_pressure = 4;</code>
     */
    var sensorPressure: kotlin.Boolean
      @JvmName("getSensorPressure")
      get() = _builder.getSensorPressure()
      @JvmName("setSensorPressure")
      set(value) {
        _builder.setSensorPressure(value)
      }
    /**
     * <code>bool sensor_pressure = 4;</code>
     */
    fun clearSensorPressure() {
      _builder.clearSensorPressure()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.PhoneModuleConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhoneModuleConfig =
  ca.berlingoqc.growbe_android_module.proto.PhoneModuleConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

