//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializephonePressureConfig")
inline fun phonePressureConfig(block: ca.berlingoqc.growbe_android_module.proto.PhonePressureConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureConfig =
  ca.berlingoqc.growbe_android_module.proto.PhonePressureConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureConfig.newBuilder()).apply { block() }._build()
object PhonePressureConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureConfig = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.PhonePressureConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhonePressureConfig =
  ca.berlingoqc.growbe_android_module.proto.PhonePressureConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

