//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializephoneStreamingConfig")
inline fun phoneStreamingConfig(block: ca.berlingoqc.growbe_android_module.proto.PhoneStreamingConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingConfig =
  ca.berlingoqc.growbe_android_module.proto.PhoneStreamingConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingConfig.newBuilder()).apply { block() }._build()
object PhoneStreamingConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingConfig = _builder.build()

    /**
     * <code>bool activated = 1;</code>
     */
    var activated: kotlin.Boolean
      @JvmName("getActivated")
      get() = _builder.getActivated()
      @JvmName("setActivated")
      set(value) {
        _builder.setActivated(value)
      }
    /**
     * <code>bool activated = 1;</code>
     */
    fun clearActivated() {
      _builder.clearActivated()
    }

    /**
     * <code>string url = 2;</code>
     */
    var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.getUrl()
      @JvmName("setUrl")
      set(value) {
        _builder.setUrl(value)
      }
    /**
     * <code>string url = 2;</code>
     */
    fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * <code>int32 camera = 3;</code>
     */
    var camera: kotlin.Int
      @JvmName("getCamera")
      get() = _builder.getCamera()
      @JvmName("setCamera")
      set(value) {
        _builder.setCamera(value)
      }
    /**
     * <code>int32 camera = 3;</code>
     */
    fun clearCamera() {
      _builder.clearCamera()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.PhoneStreamingConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.PhoneStreamingConfig =
  ca.berlingoqc.growbe_android_module.proto.PhoneStreamingConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

