//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializerect")
inline fun rect(block: ca.berlingoqc.growbe_android_module.proto.RectKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.Rect =
  ca.berlingoqc.growbe_android_module.proto.RectKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.Rect.newBuilder()).apply { block() }._build()
object RectKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.Rect.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.Rect.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.Rect = _builder.build()

    /**
     * <code>int32 top = 1;</code>
     */
    var top: kotlin.Int
      @JvmName("getTop")
      get() = _builder.getTop()
      @JvmName("setTop")
      set(value) {
        _builder.setTop(value)
      }
    /**
     * <code>int32 top = 1;</code>
     */
    fun clearTop() {
      _builder.clearTop()
    }

    /**
     * <code>int32 right = 2;</code>
     */
    var right: kotlin.Int
      @JvmName("getRight")
      get() = _builder.getRight()
      @JvmName("setRight")
      set(value) {
        _builder.setRight(value)
      }
    /**
     * <code>int32 right = 2;</code>
     */
    fun clearRight() {
      _builder.clearRight()
    }

    /**
     * <code>int32 bottom = 3;</code>
     */
    var bottom: kotlin.Int
      @JvmName("getBottom")
      get() = _builder.getBottom()
      @JvmName("setBottom")
      set(value) {
        _builder.setBottom(value)
      }
    /**
     * <code>int32 bottom = 3;</code>
     */
    fun clearBottom() {
      _builder.clearBottom()
    }

    /**
     * <code>int32 left = 4;</code>
     */
    var left: kotlin.Int
      @JvmName("getLeft")
      get() = _builder.getLeft()
      @JvmName("setLeft")
      set(value) {
        _builder.setLeft(value)
      }
    /**
     * <code>int32 left = 4;</code>
     */
    fun clearLeft() {
      _builder.clearLeft()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.Rect.copy(block: ca.berlingoqc.growbe_android_module.proto.RectKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.Rect =
  ca.berlingoqc.growbe_android_module.proto.RectKt.Dsl._create(this.toBuilder()).apply { block() }._build()

