//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializerelayOutletConfig")
inline fun relayOutletConfig(block: ca.berlingoqc.growbe_android_module.proto.RelayOutletConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletConfig =
  ca.berlingoqc.growbe_android_module.proto.RelayOutletConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletConfig.newBuilder()).apply { block() }._build()
object RelayOutletConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletConfig = _builder.build()

    /**
     * <code>.RelayOutletMode mode = 1;</code>
     */
     var mode: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletMode
      @JvmName("getMode")
      get() = _builder.getMode()
      @JvmName("setMode")
      set(value) {
        _builder.setMode(value)
      }
    /**
     * <code>.RelayOutletMode mode = 1;</code>
     */
    fun clearMode() {
      _builder.clearMode()
    }

    /**
     * <code>.AlarmConfig alarm = 2;</code>
     */
    var alarm: ca.berlingoqc.growbe_android_module.proto.Module.AlarmConfig
      @JvmName("getAlarm")
      get() = _builder.getAlarm()
      @JvmName("setAlarm")
      set(value) {
        _builder.setAlarm(value)
      }
    /**
     * <code>.AlarmConfig alarm = 2;</code>
     */
    fun clearAlarm() {
      _builder.clearAlarm()
    }
    /**
     * <code>.AlarmConfig alarm = 2;</code>
     * @return Whether the alarm field is set.
     */
    fun hasAlarm(): kotlin.Boolean {
      return _builder.hasAlarm()
    }

    /**
     * <code>.ManualConfig manual = 3;</code>
     */
    var manual: ca.berlingoqc.growbe_android_module.proto.Module.ManualConfig
      @JvmName("getManual")
      get() = _builder.getManual()
      @JvmName("setManual")
      set(value) {
        _builder.setManual(value)
      }
    /**
     * <code>.ManualConfig manual = 3;</code>
     */
    fun clearManual() {
      _builder.clearManual()
    }
    /**
     * <code>.ManualConfig manual = 3;</code>
     * @return Whether the manual field is set.
     */
    fun hasManual(): kotlin.Boolean {
      return _builder.hasManual()
    }

    /**
     * <code>.VirtualRelayConfig virtual = 4;</code>
     */
    var virtual: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayConfig
      @JvmName("getVirtual")
      get() = _builder.getVirtual()
      @JvmName("setVirtual")
      set(value) {
        _builder.setVirtual(value)
      }
    /**
     * <code>.VirtualRelayConfig virtual = 4;</code>
     */
    fun clearVirtual() {
      _builder.clearVirtual()
    }
    /**
     * <code>.VirtualRelayConfig virtual = 4;</code>
     * @return Whether the virtual field is set.
     */
    fun hasVirtual(): kotlin.Boolean {
      return _builder.hasVirtual()
    }

    /**
     * <code>.CycleConfig cycle = 5;</code>
     */
    var cycle: ca.berlingoqc.growbe_android_module.proto.Module.CycleConfig
      @JvmName("getCycle")
      get() = _builder.getCycle()
      @JvmName("setCycle")
      set(value) {
        _builder.setCycle(value)
      }
    /**
     * <code>.CycleConfig cycle = 5;</code>
     */
    fun clearCycle() {
      _builder.clearCycle()
    }
    /**
     * <code>.CycleConfig cycle = 5;</code>
     * @return Whether the cycle field is set.
     */
    fun hasCycle(): kotlin.Boolean {
      return _builder.hasCycle()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.RelayOutletConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletConfig =
  ca.berlingoqc.growbe_android_module.proto.RelayOutletConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletConfigOrBuilder.alarmOrNull: ca.berlingoqc.growbe_android_module.proto.Module.AlarmConfig?
  get() = if (hasAlarm()) getAlarm() else null

val ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletConfigOrBuilder.manualOrNull: ca.berlingoqc.growbe_android_module.proto.Module.ManualConfig?
  get() = if (hasManual()) getManual() else null

val ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletConfigOrBuilder.virtualOrNull: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayConfig?
  get() = if (hasVirtual()) getVirtual() else null

val ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletConfigOrBuilder.cycleOrNull: ca.berlingoqc.growbe_android_module.proto.Module.CycleConfig?
  get() = if (hasCycle()) getCycle() else null

