//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: board.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializerestartRequest")
inline fun restartRequest(block: ca.berlingoqc.growbe_android_module.proto.RestartRequestKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.RestartRequest =
  ca.berlingoqc.growbe_android_module.proto.RestartRequestKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Board.RestartRequest.newBuilder()).apply { block() }._build()
object RestartRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Board.RestartRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Board.RestartRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Board.RestartRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Board.RestartRequest.copy(block: ca.berlingoqc.growbe_android_module.proto.RestartRequestKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.RestartRequest =
  ca.berlingoqc.growbe_android_module.proto.RestartRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

