//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializerTCTime")
inline fun rTCTime(block: ca.berlingoqc.growbe_android_module.proto.RTCTimeKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Message.RTCTime =
  ca.berlingoqc.growbe_android_module.proto.RTCTimeKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Message.RTCTime.newBuilder()).apply { block() }._build()
object RTCTimeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Message.RTCTime.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Message.RTCTime.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Message.RTCTime = _builder.build()

    /**
     * <code>uint32 second = 1;</code>
     */
    var second: kotlin.Int
      @JvmName("getSecond")
      get() = _builder.getSecond()
      @JvmName("setSecond")
      set(value) {
        _builder.setSecond(value)
      }
    /**
     * <code>uint32 second = 1;</code>
     */
    fun clearSecond() {
      _builder.clearSecond()
    }

    /**
     * <code>uint32 minute = 2;</code>
     */
    var minute: kotlin.Int
      @JvmName("getMinute")
      get() = _builder.getMinute()
      @JvmName("setMinute")
      set(value) {
        _builder.setMinute(value)
      }
    /**
     * <code>uint32 minute = 2;</code>
     */
    fun clearMinute() {
      _builder.clearMinute()
    }

    /**
     * <code>uint32 hour = 3;</code>
     */
    var hour: kotlin.Int
      @JvmName("getHour")
      get() = _builder.getHour()
      @JvmName("setHour")
      set(value) {
        _builder.setHour(value)
      }
    /**
     * <code>uint32 hour = 3;</code>
     */
    fun clearHour() {
      _builder.clearHour()
    }

    /**
     * <code>uint32 day = 4;</code>
     */
    var day: kotlin.Int
      @JvmName("getDay")
      get() = _builder.getDay()
      @JvmName("setDay")
      set(value) {
        _builder.setDay(value)
      }
    /**
     * <code>uint32 day = 4;</code>
     */
    fun clearDay() {
      _builder.clearDay()
    }

    /**
     * <code>uint32 month = 5;</code>
     */
    var month: kotlin.Int
      @JvmName("getMonth")
      get() = _builder.getMonth()
      @JvmName("setMonth")
      set(value) {
        _builder.setMonth(value)
      }
    /**
     * <code>uint32 month = 5;</code>
     */
    fun clearMonth() {
      _builder.clearMonth()
    }

    /**
     * <code>uint32 year = 6;</code>
     */
    var year: kotlin.Int
      @JvmName("getYear")
      get() = _builder.getYear()
      @JvmName("setYear")
      set(value) {
        _builder.setYear(value)
      }
    /**
     * <code>uint32 year = 6;</code>
     */
    fun clearYear() {
      _builder.clearYear()
    }

    /**
     * <code>string tz = 7;</code>
     */
    var tz: kotlin.String
      @JvmName("getTz")
      get() = _builder.getTz()
      @JvmName("setTz")
      set(value) {
        _builder.setTz(value)
      }
    /**
     * <code>string tz = 7;</code>
     */
    fun clearTz() {
      _builder.clearTz()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Message.RTCTime.copy(block: ca.berlingoqc.growbe_android_module.proto.RTCTimeKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Message.RTCTime =
  ca.berlingoqc.growbe_android_module.proto.RTCTimeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

