//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: board.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializerunningComboard")
inline fun runningComboard(block: ca.berlingoqc.growbe_android_module.proto.RunningComboardKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.RunningComboard =
  ca.berlingoqc.growbe_android_module.proto.RunningComboardKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Board.RunningComboard.newBuilder()).apply { block() }._build()
object RunningComboardKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Board.RunningComboard.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Board.RunningComboard.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Board.RunningComboard = _builder.build()

    /**
     * <code>string imple = 1;</code>
     */
    var imple: kotlin.String
      @JvmName("getImple")
      get() = _builder.getImple()
      @JvmName("setImple")
      set(value) {
        _builder.setImple(value)
      }
    /**
     * <code>string imple = 1;</code>
     */
    fun clearImple() {
      _builder.clearImple()
    }

    /**
     * <code>string addr = 2;</code>
     */
    var addr: kotlin.String
      @JvmName("getAddr")
      get() = _builder.getAddr()
      @JvmName("setAddr")
      set(value) {
        _builder.setAddr(value)
      }
    /**
     * <code>string addr = 2;</code>
     */
    fun clearAddr() {
      _builder.clearAddr()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Board.RunningComboard.copy(block: ca.berlingoqc.growbe_android_module.proto.RunningComboardKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.RunningComboard =
  ca.berlingoqc.growbe_android_module.proto.RunningComboardKt.Dsl._create(this.toBuilder()).apply { block() }._build()

