//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializesOILCalibrationStart")
inline fun sOILCalibrationStart(block: ca.berlingoqc.growbe_android_module.proto.SOILCalibrationStartKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStart =
  ca.berlingoqc.growbe_android_module.proto.SOILCalibrationStartKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStart.newBuilder()).apply { block() }._build()
object SOILCalibrationStartKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStart.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStart.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStart = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStart.copy(block: ca.berlingoqc.growbe_android_module.proto.SOILCalibrationStartKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStart =
  ca.berlingoqc.growbe_android_module.proto.SOILCalibrationStartKt.Dsl._create(this.toBuilder()).apply { block() }._build()

