//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializesOILProbeConfig")
inline fun sOILProbeConfig(block: ca.berlingoqc.growbe_android_module.proto.SOILProbeConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig =
  ca.berlingoqc.growbe_android_module.proto.SOILProbeConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig.newBuilder()).apply { block() }._build()
object SOILProbeConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig = _builder.build()

    /**
     * <code>int32 low = 1;</code>
     */
    var low: kotlin.Int
      @JvmName("getLow")
      get() = _builder.getLow()
      @JvmName("setLow")
      set(value) {
        _builder.setLow(value)
      }
    /**
     * <code>int32 low = 1;</code>
     */
    fun clearLow() {
      _builder.clearLow()
    }

    /**
     * <code>int32 high = 2;</code>
     */
    var high: kotlin.Int
      @JvmName("getHigh")
      get() = _builder.getHigh()
      @JvmName("setHigh")
      set(value) {
        _builder.setHigh(value)
      }
    /**
     * <code>int32 high = 2;</code>
     */
    fun clearHigh() {
      _builder.clearHigh()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.SOILProbeConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig =
  ca.berlingoqc.growbe_android_module.proto.SOILProbeConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

