//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializesOILCalibrationStep")
inline fun sOILCalibrationStep(block: ca.berlingoqc.growbe_android_module.proto.SOILCalibrationStepKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStep =
  ca.berlingoqc.growbe_android_module.proto.SOILCalibrationStepKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStep.newBuilder()).apply { block() }._build()
object SOILCalibrationStepKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStep.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStep.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStep = _builder.build()

    /**
     * <code>.CalibrationStep requested_step = 1;</code>
     */
     var requestedStep: ca.berlingoqc.growbe_android_module.proto.Module.CalibrationStep
      @JvmName("getRequestedStep")
      get() = _builder.getRequestedStep()
      @JvmName("setRequestedStep")
      set(value) {
        _builder.setRequestedStep(value)
      }
    /**
     * <code>.CalibrationStep requested_step = 1;</code>
     */
    fun clearRequestedStep() {
      _builder.clearRequestedStep()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStep.copy(block: ca.berlingoqc.growbe_android_module.proto.SOILCalibrationStepKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStep =
  ca.berlingoqc.growbe_android_module.proto.SOILCalibrationStepKt.Dsl._create(this.toBuilder()).apply { block() }._build()

