//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializesOILModuleConfig")
inline fun sOILModuleConfig(block: ca.berlingoqc.growbe_android_module.proto.SOILModuleConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfig =
  ca.berlingoqc.growbe_android_module.proto.SOILModuleConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfig.newBuilder()).apply { block() }._build()
object SOILModuleConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfig = _builder.build()

    /**
     * <code>.SOILProbeConfig p0 = 1;</code>
     */
    var p0: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig
      @JvmName("getP0")
      get() = _builder.getP0()
      @JvmName("setP0")
      set(value) {
        _builder.setP0(value)
      }
    /**
     * <code>.SOILProbeConfig p0 = 1;</code>
     */
    fun clearP0() {
      _builder.clearP0()
    }
    /**
     * <code>.SOILProbeConfig p0 = 1;</code>
     * @return Whether the p0 field is set.
     */
    fun hasP0(): kotlin.Boolean {
      return _builder.hasP0()
    }

    /**
     * <code>.SOILProbeConfig p1 = 2;</code>
     */
    var p1: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig
      @JvmName("getP1")
      get() = _builder.getP1()
      @JvmName("setP1")
      set(value) {
        _builder.setP1(value)
      }
    /**
     * <code>.SOILProbeConfig p1 = 2;</code>
     */
    fun clearP1() {
      _builder.clearP1()
    }
    /**
     * <code>.SOILProbeConfig p1 = 2;</code>
     * @return Whether the p1 field is set.
     */
    fun hasP1(): kotlin.Boolean {
      return _builder.hasP1()
    }

    /**
     * <code>.SOILProbeConfig p2 = 3;</code>
     */
    var p2: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig
      @JvmName("getP2")
      get() = _builder.getP2()
      @JvmName("setP2")
      set(value) {
        _builder.setP2(value)
      }
    /**
     * <code>.SOILProbeConfig p2 = 3;</code>
     */
    fun clearP2() {
      _builder.clearP2()
    }
    /**
     * <code>.SOILProbeConfig p2 = 3;</code>
     * @return Whether the p2 field is set.
     */
    fun hasP2(): kotlin.Boolean {
      return _builder.hasP2()
    }

    /**
     * <code>.SOILProbeConfig p3 = 4;</code>
     */
    var p3: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig
      @JvmName("getP3")
      get() = _builder.getP3()
      @JvmName("setP3")
      set(value) {
        _builder.setP3(value)
      }
    /**
     * <code>.SOILProbeConfig p3 = 4;</code>
     */
    fun clearP3() {
      _builder.clearP3()
    }
    /**
     * <code>.SOILProbeConfig p3 = 4;</code>
     * @return Whether the p3 field is set.
     */
    fun hasP3(): kotlin.Boolean {
      return _builder.hasP3()
    }

    /**
     * <code>.SOILProbeConfig p4 = 5;</code>
     */
    var p4: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig
      @JvmName("getP4")
      get() = _builder.getP4()
      @JvmName("setP4")
      set(value) {
        _builder.setP4(value)
      }
    /**
     * <code>.SOILProbeConfig p4 = 5;</code>
     */
    fun clearP4() {
      _builder.clearP4()
    }
    /**
     * <code>.SOILProbeConfig p4 = 5;</code>
     * @return Whether the p4 field is set.
     */
    fun hasP4(): kotlin.Boolean {
      return _builder.hasP4()
    }

    /**
     * <code>.SOILProbeConfig p5 = 6;</code>
     */
    var p5: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig
      @JvmName("getP5")
      get() = _builder.getP5()
      @JvmName("setP5")
      set(value) {
        _builder.setP5(value)
      }
    /**
     * <code>.SOILProbeConfig p5 = 6;</code>
     */
    fun clearP5() {
      _builder.clearP5()
    }
    /**
     * <code>.SOILProbeConfig p5 = 6;</code>
     * @return Whether the p5 field is set.
     */
    fun hasP5(): kotlin.Boolean {
      return _builder.hasP5()
    }

    /**
     * <code>.SOILProbeConfig p6 = 7;</code>
     */
    var p6: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig
      @JvmName("getP6")
      get() = _builder.getP6()
      @JvmName("setP6")
      set(value) {
        _builder.setP6(value)
      }
    /**
     * <code>.SOILProbeConfig p6 = 7;</code>
     */
    fun clearP6() {
      _builder.clearP6()
    }
    /**
     * <code>.SOILProbeConfig p6 = 7;</code>
     * @return Whether the p6 field is set.
     */
    fun hasP6(): kotlin.Boolean {
      return _builder.hasP6()
    }

    /**
     * <code>.SOILProbeConfig p7 = 8;</code>
     */
    var p7: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig
      @JvmName("getP7")
      get() = _builder.getP7()
      @JvmName("setP7")
      set(value) {
        _builder.setP7(value)
      }
    /**
     * <code>.SOILProbeConfig p7 = 8;</code>
     */
    fun clearP7() {
      _builder.clearP7()
    }
    /**
     * <code>.SOILProbeConfig p7 = 8;</code>
     * @return Whether the p7 field is set.
     */
    fun hasP7(): kotlin.Boolean {
      return _builder.hasP7()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.SOILModuleConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfig =
  ca.berlingoqc.growbe_android_module.proto.SOILModuleConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfigOrBuilder.p0OrNull: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig?
  get() = if (hasP0()) getP0() else null

val ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfigOrBuilder.p1OrNull: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig?
  get() = if (hasP1()) getP1() else null

val ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfigOrBuilder.p2OrNull: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig?
  get() = if (hasP2()) getP2() else null

val ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfigOrBuilder.p3OrNull: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig?
  get() = if (hasP3()) getP3() else null

val ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfigOrBuilder.p4OrNull: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig?
  get() = if (hasP4()) getP4() else null

val ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfigOrBuilder.p5OrNull: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig?
  get() = if (hasP5()) getP5() else null

val ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfigOrBuilder.p6OrNull: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig?
  get() = if (hasP6()) getP6() else null

val ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleConfigOrBuilder.p7OrNull: ca.berlingoqc.growbe_android_module.proto.Module.SOILProbeConfig?
  get() = if (hasP7()) getP7() else null

