//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializesOILCalibrationStepEvent")
inline fun sOILCalibrationStepEvent(block: ca.berlingoqc.growbe_android_module.proto.SOILCalibrationStepEventKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStepEvent =
  ca.berlingoqc.growbe_android_module.proto.SOILCalibrationStepEventKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStepEvent.newBuilder()).apply { block() }._build()
object SOILCalibrationStepEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStepEvent.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStepEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStepEvent = _builder.build()

    /**
     * <code>.CalibrationStep step = 1;</code>
     */
     var step: ca.berlingoqc.growbe_android_module.proto.Module.CalibrationStep
      @JvmName("getStep")
      get() = _builder.getStep()
      @JvmName("setStep")
      set(value) {
        _builder.setStep(value)
      }
    /**
     * <code>.CalibrationStep step = 1;</code>
     */
    fun clearStep() {
      _builder.clearStep()
    }

    /**
     * <code>.CalibrationStepStatus status = 2;</code>
     */
     var status: ca.berlingoqc.growbe_android_module.proto.Module.CalibrationStepStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <code>.CalibrationStepStatus status = 2;</code>
     */
    fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * <code>.CalibrationError erro = 3;</code>
     */
     var erro: ca.berlingoqc.growbe_android_module.proto.Module.CalibrationError
      @JvmName("getErro")
      get() = _builder.getErro()
      @JvmName("setErro")
      set(value) {
        _builder.setErro(value)
      }
    /**
     * <code>.CalibrationError erro = 3;</code>
     */
    fun clearErro() {
      _builder.clearErro()
    }

    /**
     * <code>string messag = 4;</code>
     */
    var messag: kotlin.String
      @JvmName("getMessag")
      get() = _builder.getMessag()
      @JvmName("setMessag")
      set(value) {
        _builder.setMessag(value)
      }
    /**
     * <code>string messag = 4;</code>
     */
    fun clearMessag() {
      _builder.clearMessag()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class LowProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .SOILModuleData low = 5;</code>
     */
     val low: com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, LowProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getLowList()
      )
    /**
     * <code>repeated .SOILModuleData low = 5;</code>
     * @param value The low to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addLow")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, LowProxy>.add(value: ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData) {
      _builder.addLow(value)
    }
    /**
     * <code>repeated .SOILModuleData low = 5;</code>
     * @param value The low to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignLow")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, LowProxy>.plusAssign(value: ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData) {
      add(value)
    }
    /**
     * <code>repeated .SOILModuleData low = 5;</code>
     * @param values The low to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllLow")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, LowProxy>.addAll(values: kotlin.collections.Iterable<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData>) {
      _builder.addAllLow(values)
    }
    /**
     * <code>repeated .SOILModuleData low = 5;</code>
     * @param values The low to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllLow")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, LowProxy>.plusAssign(values: kotlin.collections.Iterable<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData>) {
      addAll(values)
    }
    /**
     * <code>repeated .SOILModuleData low = 5;</code>
     * @param index The index to set the value at.
     * @param value The low to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setLow")
    operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, LowProxy>.set(index: kotlin.Int, value: ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData) {
      _builder.setLow(index, value)
    }
    /**
     * <code>repeated .SOILModuleData low = 5;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearLow")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, LowProxy>.clear() {
      _builder.clearLow()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class HighProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .SOILModuleData high = 6;</code>
     */
     val high: com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, HighProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getHighList()
      )
    /**
     * <code>repeated .SOILModuleData high = 6;</code>
     * @param value The high to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addHigh")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, HighProxy>.add(value: ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData) {
      _builder.addHigh(value)
    }
    /**
     * <code>repeated .SOILModuleData high = 6;</code>
     * @param value The high to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignHigh")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, HighProxy>.plusAssign(value: ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData) {
      add(value)
    }
    /**
     * <code>repeated .SOILModuleData high = 6;</code>
     * @param values The high to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllHigh")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, HighProxy>.addAll(values: kotlin.collections.Iterable<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData>) {
      _builder.addAllHigh(values)
    }
    /**
     * <code>repeated .SOILModuleData high = 6;</code>
     * @param values The high to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllHigh")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, HighProxy>.plusAssign(values: kotlin.collections.Iterable<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData>) {
      addAll(values)
    }
    /**
     * <code>repeated .SOILModuleData high = 6;</code>
     * @param index The index to set the value at.
     * @param value The high to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setHigh")
    operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, HighProxy>.set(index: kotlin.Int, value: ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData) {
      _builder.setHigh(index, value)
    }
    /**
     * <code>repeated .SOILModuleData high = 6;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearHigh")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.SOILModuleData, HighProxy>.clear() {
      _builder.clearHigh()
    }

  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStepEvent.copy(block: ca.berlingoqc.growbe_android_module.proto.SOILCalibrationStepEventKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.SOILCalibrationStepEvent =
  ca.berlingoqc.growbe_android_module.proto.SOILCalibrationStepEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

