//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializetHLModuleData")
inline fun tHLModuleData(block: ca.berlingoqc.growbe_android_module.proto.THLModuleDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.THLModuleData =
  ca.berlingoqc.growbe_android_module.proto.THLModuleDataKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.THLModuleData.newBuilder()).apply { block() }._build()
object THLModuleDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.THLModuleData.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.THLModuleData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.THLModuleData = _builder.build()

    /**
     * <code>float humidity = 2;</code>
     */
    var humidity: kotlin.Float
      @JvmName("getHumidity")
      get() = _builder.getHumidity()
      @JvmName("setHumidity")
      set(value) {
        _builder.setHumidity(value)
      }
    /**
     * <code>float humidity = 2;</code>
     */
    fun clearHumidity() {
      _builder.clearHumidity()
    }

    /**
     * <code>float airTemperature = 3;</code>
     */
    var airTemperature: kotlin.Float
      @JvmName("getAirTemperature")
      get() = _builder.getAirTemperature()
      @JvmName("setAirTemperature")
      set(value) {
        _builder.setAirTemperature(value)
      }
    /**
     * <code>float airTemperature = 3;</code>
     */
    fun clearAirTemperature() {
      _builder.clearAirTemperature()
    }

    /**
     * <code>int32 timestamp = 9;</code>
     */
    var timestamp: kotlin.Int
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * <code>int32 timestamp = 9;</code>
     */
    fun clearTimestamp() {
      _builder.clearTimestamp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.THLModuleData.copy(block: ca.berlingoqc.growbe_android_module.proto.THLModuleDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.THLModuleData =
  ca.berlingoqc.growbe_android_module.proto.THLModuleDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

