//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: board.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializeupdateExecute")
inline fun updateExecute(block: ca.berlingoqc.growbe_android_module.proto.UpdateExecuteKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.UpdateExecute =
  ca.berlingoqc.growbe_android_module.proto.UpdateExecuteKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Board.UpdateExecute.newBuilder()).apply { block() }._build()
object UpdateExecuteKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Board.UpdateExecute.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Board.UpdateExecute.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Board.UpdateExecute = _builder.build()

    /**
     * <code>string version = 1;</code>
     */
    var version: kotlin.String
      @JvmName("getVersion")
      get() = _builder.getVersion()
      @JvmName("setVersion")
      set(value) {
        _builder.setVersion(value)
      }
    /**
     * <code>string version = 1;</code>
     */
    fun clearVersion() {
      _builder.clearVersion()
    }

    /**
     * <code>bool restarted = 2;</code>
     */
    var restarted: kotlin.Boolean
      @JvmName("getRestarted")
      get() = _builder.getRestarted()
      @JvmName("setRestarted")
      set(value) {
        _builder.setRestarted(value)
      }
    /**
     * <code>bool restarted = 2;</code>
     */
    fun clearRestarted() {
      _builder.clearRestarted()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Board.UpdateExecute.copy(block: ca.berlingoqc.growbe_android_module.proto.UpdateExecuteKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.UpdateExecute =
  ca.berlingoqc.growbe_android_module.proto.UpdateExecuteKt.Dsl._create(this.toBuilder()).apply { block() }._build()

