//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: board.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializeupdaterConfig")
inline fun updaterConfig(block: ca.berlingoqc.growbe_android_module.proto.UpdaterConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.UpdaterConfig =
  ca.berlingoqc.growbe_android_module.proto.UpdaterConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Board.UpdaterConfig.newBuilder()).apply { block() }._build()
object UpdaterConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Board.UpdaterConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Board.UpdaterConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Board.UpdaterConfig = _builder.build()

    /**
     * <code>bool autoupdate = 1;</code>
     */
    var autoupdate: kotlin.Boolean
      @JvmName("getAutoupdate")
      get() = _builder.getAutoupdate()
      @JvmName("setAutoupdate")
      set(value) {
        _builder.setAutoupdate(value)
      }
    /**
     * <code>bool autoupdate = 1;</code>
     */
    fun clearAutoupdate() {
      _builder.clearAutoupdate()
    }

    /**
     * <code>string channel = 2;</code>
     */
    var channel: kotlin.String
      @JvmName("getChannel")
      get() = _builder.getChannel()
      @JvmName("setChannel")
      set(value) {
        _builder.setChannel(value)
      }
    /**
     * <code>string channel = 2;</code>
     */
    fun clearChannel() {
      _builder.clearChannel()
    }

    /**
     * <code>bool reboot = 3;</code>
     */
    var reboot: kotlin.Boolean
      @JvmName("getReboot")
      get() = _builder.getReboot()
      @JvmName("setReboot")
      set(value) {
        _builder.setReboot(value)
      }
    /**
     * <code>bool reboot = 3;</code>
     */
    fun clearReboot() {
      _builder.clearReboot()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Board.UpdaterConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.UpdaterConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Board.UpdaterConfig =
  ca.berlingoqc.growbe_android_module.proto.UpdaterConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

