//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializevirtualRelayData")
inline fun virtualRelayData(block: ca.berlingoqc.growbe_android_module.proto.VirtualRelayDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayData =
  ca.berlingoqc.growbe_android_module.proto.VirtualRelayDataKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayData.newBuilder()).apply { block() }._build()
object VirtualRelayDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayData.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayData = _builder.build()

    /**
     * <code>.RelayOutletData data = 1;</code>
     */
    var data: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * <code>.RelayOutletData data = 1;</code>
     */
    fun clearData() {
      _builder.clearData()
    }
    /**
     * <code>.RelayOutletData data = 1;</code>
     * @return Whether the data field is set.
     */
    fun hasData(): kotlin.Boolean {
      return _builder.hasData()
    }

    /**
     * <code>int32 timestamp = 2;</code>
     */
    var timestamp: kotlin.Int
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * <code>int32 timestamp = 2;</code>
     */
    fun clearTimestamp() {
      _builder.clearTimestamp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayData.copy(block: ca.berlingoqc.growbe_android_module.proto.VirtualRelayDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayData =
  ca.berlingoqc.growbe_android_module.proto.VirtualRelayDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayDataOrBuilder.dataOrNull: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData?
  get() = if (hasData()) getData() else null

