//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializevirtualRelayItem")
inline fun virtualRelayItem(block: ca.berlingoqc.growbe_android_module.proto.VirtualRelayItemKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayItem =
  ca.berlingoqc.growbe_android_module.proto.VirtualRelayItemKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayItem.newBuilder()).apply { block() }._build()
object VirtualRelayItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayItem.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayItem = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class PropertiesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * action port for the properties
     * </pre>
     *
     * <code>repeated .VirtualRelayPropertyConfig properties = 1;</code>
     */
     val properties: com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayPropertyConfig, PropertiesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getPropertiesList()
      )
    /**
     * <pre>
     * action port for the properties
     * </pre>
     *
     * <code>repeated .VirtualRelayPropertyConfig properties = 1;</code>
     * @param value The properties to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addProperties")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayPropertyConfig, PropertiesProxy>.add(value: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayPropertyConfig) {
      _builder.addProperties(value)
    }
    /**
     * <pre>
     * action port for the properties
     * </pre>
     *
     * <code>repeated .VirtualRelayPropertyConfig properties = 1;</code>
     * @param value The properties to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignProperties")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayPropertyConfig, PropertiesProxy>.plusAssign(value: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayPropertyConfig) {
      add(value)
    }
    /**
     * <pre>
     * action port for the properties
     * </pre>
     *
     * <code>repeated .VirtualRelayPropertyConfig properties = 1;</code>
     * @param values The properties to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllProperties")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayPropertyConfig, PropertiesProxy>.addAll(values: kotlin.collections.Iterable<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayPropertyConfig>) {
      _builder.addAllProperties(values)
    }
    /**
     * <pre>
     * action port for the properties
     * </pre>
     *
     * <code>repeated .VirtualRelayPropertyConfig properties = 1;</code>
     * @param values The properties to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllProperties")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayPropertyConfig, PropertiesProxy>.plusAssign(values: kotlin.collections.Iterable<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayPropertyConfig>) {
      addAll(values)
    }
    /**
     * <pre>
     * action port for the properties
     * </pre>
     *
     * <code>repeated .VirtualRelayPropertyConfig properties = 1;</code>
     * @param index The index to set the value at.
     * @param value The properties to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setProperties")
    operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayPropertyConfig, PropertiesProxy>.set(index: kotlin.Int, value: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayPropertyConfig) {
      _builder.setProperties(index, value)
    }
    /**
     * <pre>
     * action port for the properties
     * </pre>
     *
     * <code>repeated .VirtualRelayPropertyConfig properties = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearProperties")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayPropertyConfig, PropertiesProxy>.clear() {
      _builder.clearProperties()
    }

  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayItem.copy(block: ca.berlingoqc.growbe_android_module.proto.VirtualRelayItemKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayItem =
  ca.berlingoqc.growbe_android_module.proto.VirtualRelayItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

