//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializevirtualRelays")
inline fun virtualRelays(block: ca.berlingoqc.growbe_android_module.proto.VirtualRelaysKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelays =
  ca.berlingoqc.growbe_android_module.proto.VirtualRelaysKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelays.newBuilder()).apply { block() }._build()
object VirtualRelaysKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelays.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelays.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelays = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class RelaysProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .VirtualRelay relays = 1;</code>
     */
     val relays: com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelay, RelaysProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRelaysList()
      )
    /**
     * <code>repeated .VirtualRelay relays = 1;</code>
     * @param value The relays to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRelays")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelay, RelaysProxy>.add(value: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelay) {
      _builder.addRelays(value)
    }
    /**
     * <code>repeated .VirtualRelay relays = 1;</code>
     * @param value The relays to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRelays")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelay, RelaysProxy>.plusAssign(value: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelay) {
      add(value)
    }
    /**
     * <code>repeated .VirtualRelay relays = 1;</code>
     * @param values The relays to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRelays")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelay, RelaysProxy>.addAll(values: kotlin.collections.Iterable<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelay>) {
      _builder.addAllRelays(values)
    }
    /**
     * <code>repeated .VirtualRelay relays = 1;</code>
     * @param values The relays to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRelays")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelay, RelaysProxy>.plusAssign(values: kotlin.collections.Iterable<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelay>) {
      addAll(values)
    }
    /**
     * <code>repeated .VirtualRelay relays = 1;</code>
     * @param index The index to set the value at.
     * @param value The relays to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRelays")
    operator fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelay, RelaysProxy>.set(index: kotlin.Int, value: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelay) {
      _builder.setRelays(index, value)
    }
    /**
     * <code>repeated .VirtualRelay relays = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRelays")
    fun com.google.protobuf.kotlin.DslList<ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelay, RelaysProxy>.clear() {
      _builder.clearRelays()
    }

  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelays.copy(block: ca.berlingoqc.growbe_android_module.proto.VirtualRelaysKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelays =
  ca.berlingoqc.growbe_android_module.proto.VirtualRelaysKt.Dsl._create(this.toBuilder()).apply { block() }._build()

