//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializevirtualRelayConfig")
inline fun virtualRelayConfig(block: ca.berlingoqc.growbe_android_module.proto.VirtualRelayConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayConfig =
  ca.berlingoqc.growbe_android_module.proto.VirtualRelayConfigKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayConfig.newBuilder()).apply { block() }._build()
object VirtualRelayConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayConfig.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayConfig = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayConfig.copy(block: ca.berlingoqc.growbe_android_module.proto.VirtualRelayConfigKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.VirtualRelayConfig =
  ca.berlingoqc.growbe_android_module.proto.VirtualRelayConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

