//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializewAModuleData")
inline fun wAModuleData(block: ca.berlingoqc.growbe_android_module.proto.WAModuleDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.WAModuleData =
  ca.berlingoqc.growbe_android_module.proto.WAModuleDataKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.WAModuleData.newBuilder()).apply { block() }._build()
object WAModuleDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.WAModuleData.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.WAModuleData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.WAModuleData = _builder.build()

    /**
     * <code>int32 PH = 2;</code>
     */
    var pH: kotlin.Int
      @JvmName("getPH")
      get() = _builder.getPH()
      @JvmName("setPH")
      set(value) {
        _builder.setPH(value)
      }
    /**
     * <code>int32 PH = 2;</code>
     */
    fun clearPH() {
      _builder.clearPH()
    }

    /**
     * <code>int32 EC = 3;</code>
     */
    var eC: kotlin.Int
      @JvmName("getEC")
      get() = _builder.getEC()
      @JvmName("setEC")
      set(value) {
        _builder.setEC(value)
      }
    /**
     * <code>int32 EC = 3;</code>
     */
    fun clearEC() {
      _builder.clearEC()
    }

    /**
     * <code>int32 temperature = 4;</code>
     */
    var temperature: kotlin.Int
      @JvmName("getTemperature")
      get() = _builder.getTemperature()
      @JvmName("setTemperature")
      set(value) {
        _builder.setTemperature(value)
      }
    /**
     * <code>int32 temperature = 4;</code>
     */
    fun clearTemperature() {
      _builder.clearTemperature()
    }

    /**
     * <code>int32 timestamp = 9;</code>
     */
    var timestamp: kotlin.Int
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * <code>int32 timestamp = 9;</code>
     */
    fun clearTimestamp() {
      _builder.clearTimestamp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.WAModuleData.copy(block: ca.berlingoqc.growbe_android_module.proto.WAModuleDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.WAModuleData =
  ca.berlingoqc.growbe_android_module.proto.WAModuleDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

