//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: module.proto

package ca.berlingoqc.growbe_android_module.proto;

@kotlin.jvm.JvmName("-initializewCModuleData")
inline fun wCModuleData(block: ca.berlingoqc.growbe_android_module.proto.WCModuleDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.WCModuleData =
  ca.berlingoqc.growbe_android_module.proto.WCModuleDataKt.Dsl._create(ca.berlingoqc.growbe_android_module.proto.Module.WCModuleData.newBuilder()).apply { block() }._build()
object WCModuleDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: ca.berlingoqc.growbe_android_module.proto.Module.WCModuleData.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ca.berlingoqc.growbe_android_module.proto.Module.WCModuleData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ca.berlingoqc.growbe_android_module.proto.Module.WCModuleData = _builder.build()

    /**
     * <code>.RelayOutletData p0 = 1;</code>
     */
    var p0: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData
      @JvmName("getP0")
      get() = _builder.getP0()
      @JvmName("setP0")
      set(value) {
        _builder.setP0(value)
      }
    /**
     * <code>.RelayOutletData p0 = 1;</code>
     */
    fun clearP0() {
      _builder.clearP0()
    }
    /**
     * <code>.RelayOutletData p0 = 1;</code>
     * @return Whether the p0 field is set.
     */
    fun hasP0(): kotlin.Boolean {
      return _builder.hasP0()
    }

    /**
     * <code>.RelayOutletData p1 = 2;</code>
     */
    var p1: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData
      @JvmName("getP1")
      get() = _builder.getP1()
      @JvmName("setP1")
      set(value) {
        _builder.setP1(value)
      }
    /**
     * <code>.RelayOutletData p1 = 2;</code>
     */
    fun clearP1() {
      _builder.clearP1()
    }
    /**
     * <code>.RelayOutletData p1 = 2;</code>
     * @return Whether the p1 field is set.
     */
    fun hasP1(): kotlin.Boolean {
      return _builder.hasP1()
    }

    /**
     * <code>.RelayOutletData p2 = 3;</code>
     */
    var p2: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData
      @JvmName("getP2")
      get() = _builder.getP2()
      @JvmName("setP2")
      set(value) {
        _builder.setP2(value)
      }
    /**
     * <code>.RelayOutletData p2 = 3;</code>
     */
    fun clearP2() {
      _builder.clearP2()
    }
    /**
     * <code>.RelayOutletData p2 = 3;</code>
     * @return Whether the p2 field is set.
     */
    fun hasP2(): kotlin.Boolean {
      return _builder.hasP2()
    }

    /**
     * <code>.RelayOutletData drain = 4;</code>
     */
    var drain: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData
      @JvmName("getDrain")
      get() = _builder.getDrain()
      @JvmName("setDrain")
      set(value) {
        _builder.setDrain(value)
      }
    /**
     * <code>.RelayOutletData drain = 4;</code>
     */
    fun clearDrain() {
      _builder.clearDrain()
    }
    /**
     * <code>.RelayOutletData drain = 4;</code>
     * @return Whether the drain field is set.
     */
    fun hasDrain(): kotlin.Boolean {
      return _builder.hasDrain()
    }

    /**
     * <code>.RelayOutletData pump0 = 5;</code>
     */
    var pump0: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData
      @JvmName("getPump0")
      get() = _builder.getPump0()
      @JvmName("setPump0")
      set(value) {
        _builder.setPump0(value)
      }
    /**
     * <code>.RelayOutletData pump0 = 5;</code>
     */
    fun clearPump0() {
      _builder.clearPump0()
    }
    /**
     * <code>.RelayOutletData pump0 = 5;</code>
     * @return Whether the pump0 field is set.
     */
    fun hasPump0(): kotlin.Boolean {
      return _builder.hasPump0()
    }

    /**
     * <code>.RelayOutletData pump1 = 6;</code>
     */
    var pump1: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData
      @JvmName("getPump1")
      get() = _builder.getPump1()
      @JvmName("setPump1")
      set(value) {
        _builder.setPump1(value)
      }
    /**
     * <code>.RelayOutletData pump1 = 6;</code>
     */
    fun clearPump1() {
      _builder.clearPump1()
    }
    /**
     * <code>.RelayOutletData pump1 = 6;</code>
     * @return Whether the pump1 field is set.
     */
    fun hasPump1(): kotlin.Boolean {
      return _builder.hasPump1()
    }

    /**
     * <code>.RelayOutletData pump2 = 7;</code>
     */
    var pump2: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData
      @JvmName("getPump2")
      get() = _builder.getPump2()
      @JvmName("setPump2")
      set(value) {
        _builder.setPump2(value)
      }
    /**
     * <code>.RelayOutletData pump2 = 7;</code>
     */
    fun clearPump2() {
      _builder.clearPump2()
    }
    /**
     * <code>.RelayOutletData pump2 = 7;</code>
     * @return Whether the pump2 field is set.
     */
    fun hasPump2(): kotlin.Boolean {
      return _builder.hasPump2()
    }

    /**
     * <code>.RelayOutletData pump3 = 8;</code>
     */
    var pump3: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData
      @JvmName("getPump3")
      get() = _builder.getPump3()
      @JvmName("setPump3")
      set(value) {
        _builder.setPump3(value)
      }
    /**
     * <code>.RelayOutletData pump3 = 8;</code>
     */
    fun clearPump3() {
      _builder.clearPump3()
    }
    /**
     * <code>.RelayOutletData pump3 = 8;</code>
     * @return Whether the pump3 field is set.
     */
    fun hasPump3(): kotlin.Boolean {
      return _builder.hasPump3()
    }

    /**
     * <code>int32 timestamp = 9;</code>
     */
    var timestamp: kotlin.Int
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * <code>int32 timestamp = 9;</code>
     */
    fun clearTimestamp() {
      _builder.clearTimestamp()
    }

    /**
     * <code>.Actor actor = 10;</code>
     */
    var actor: ca.berlingoqc.growbe_android_module.proto.Module.Actor
      @JvmName("getActor")
      get() = _builder.getActor()
      @JvmName("setActor")
      set(value) {
        _builder.setActor(value)
      }
    /**
     * <code>.Actor actor = 10;</code>
     */
    fun clearActor() {
      _builder.clearActor()
    }
    /**
     * <code>.Actor actor = 10;</code>
     * @return Whether the actor field is set.
     */
    fun hasActor(): kotlin.Boolean {
      return _builder.hasActor()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ca.berlingoqc.growbe_android_module.proto.Module.WCModuleData.copy(block: ca.berlingoqc.growbe_android_module.proto.WCModuleDataKt.Dsl.() -> kotlin.Unit): ca.berlingoqc.growbe_android_module.proto.Module.WCModuleData =
  ca.berlingoqc.growbe_android_module.proto.WCModuleDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val ca.berlingoqc.growbe_android_module.proto.Module.WCModuleDataOrBuilder.p0OrNull: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData?
  get() = if (hasP0()) getP0() else null

val ca.berlingoqc.growbe_android_module.proto.Module.WCModuleDataOrBuilder.p1OrNull: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData?
  get() = if (hasP1()) getP1() else null

val ca.berlingoqc.growbe_android_module.proto.Module.WCModuleDataOrBuilder.p2OrNull: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData?
  get() = if (hasP2()) getP2() else null

val ca.berlingoqc.growbe_android_module.proto.Module.WCModuleDataOrBuilder.drainOrNull: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData?
  get() = if (hasDrain()) getDrain() else null

val ca.berlingoqc.growbe_android_module.proto.Module.WCModuleDataOrBuilder.pump0OrNull: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData?
  get() = if (hasPump0()) getPump0() else null

val ca.berlingoqc.growbe_android_module.proto.Module.WCModuleDataOrBuilder.pump1OrNull: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData?
  get() = if (hasPump1()) getPump1() else null

val ca.berlingoqc.growbe_android_module.proto.Module.WCModuleDataOrBuilder.pump2OrNull: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData?
  get() = if (hasPump2()) getPump2() else null

val ca.berlingoqc.growbe_android_module.proto.Module.WCModuleDataOrBuilder.pump3OrNull: ca.berlingoqc.growbe_android_module.proto.Module.RelayOutletData?
  get() = if (hasPump3()) getPump3() else null

val ca.berlingoqc.growbe_android_module.proto.Module.WCModuleDataOrBuilder.actorOrNull: ca.berlingoqc.growbe_android_module.proto.Module.Actor?
  get() = if (hasActor()) getActor() else null

